"""
Problen 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:
1   2   3   5   8   13  21  34  55  89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

1       2     3
odd + even = odd

2       3     5
even + odd = odd

3      5     8
odd + odd = even

5 = 2 + (1 + 2)
5 = l + 2g

8 = (1 + 2) + (1 + 2 + 2)
8 = 2l + 3g
"""

def sum_even_fibs(limit: int = 4000000) -> None:
    total = 0
    lesser, greater = 1, 2
    while greater < limit:
        total += greater
        templ, tempg = lesser, greater
        lesser = templ + 2 * tempg
        greater = 2 * lesser - tempg
    print(total)


if __name__ == "__main__":
    print(2 + 8 + 34)
    sum_even_fibs(35)
    sum_even_fibs()
            